### ISSUE TITLE
`licenses` module: missing slides

### ISSUE THREAD

**Issue by Cmurilochem** [esciencecenter-digital-skills/research-software-support#37]
It looks like that the slides from the `licenses` module are not contained within the `modules/licenses`.  Maybe they were deleted on the way ? or put in different path ?

**Comment by LourensVeen** [comment]
Hmm, it looks like #24 removed them, but I don't think that that was intentional. They were supposed to be moved to a different directory I think? Where are they supposed to be in the new system?

**Comment by Cmurilochem** [comment]
> Hmm, it looks like #24 removed them, but I don't think that that was intentional. They were supposed to be moved to a different directory I think? Where are they supposed to be in the new system?

Yes, please, could you put them outside `media` (but inside `/modules/licenses`) ?
