### ISSUE TITLE
Licensing section has weird section headers

### ISSUE THREAD

**Issue by LourensVeen** [esciencecenter-digital-skills/research-software-support#51]
It looks like the headers (tabs?) at the top of the page are made from the file names, and I didn't anticipate that when I created the files for the licensing section, so they look a bit funny ("ExHaveLicensingPolicy"). Or maybe that's a fallback and I need to change the way the header of the page is written for it to be picked up. Anyway, needs fixing.

**Comment by JaroCamphuijsen** [comment]
Yeah filenames are not the best thing to take for menu items, I agree. But then again, Nuxt works in mysterious.. oh no, intuitive ways. Right @raar1 ?

My idea would be to have a block of configuration settings at the top of each of the content markdown files. The block would be similar to in [the `license.md` file in the `module` directory](https://github.com/esciencecenter-digital-skills/research-software-support/blob/6bf0cc5a40138d6c53a4de1e3aabae8cf4701552/modules/licenses.md?plain=1#L1C1-L9C4)

So for example:

```md
---
title: Policies
---
```
We probably want to collect more information in this header eventually.

**Comment by JaroCamphuijsen** [comment]
Hi @LourensVeen,
I just want to let you know that it is currently possible to add a header with metadata to your markdown files like this:

```markdown
<!--- modules/03.university_policy.md --->
---
title: University policies
---
```
It will render the title of the chapter accordingly.
However, currently this will not work for the slides (.pmd) file. Well, actually it will work, but then it will also create a slide in the reveal.js slideshow. So there, preferably the first slide will actually hold the title that will also show up as a chapter tab. We will work on making this more similar to the other markdowns.

**Comment by Cmurilochem** [comment]
@LourensVeen. Also, I am not sure if the ordering of the reading material is correct. If you want, you can change it in the header via the `order` option
```
---
title: Copyright and software
type: reading
order: 2
---
```
Alternatively, you can send me the correct order, and titles and I can update.

**Comment by JaroCamphuijsen** [comment]
@LourensVeen Do you agree that we close this issue, as it was solved in https://github.com/esciencecenter-digital-skills/research-software-support/pull/57? In your next module update you can always change the chapter titles if you want. I'm closing the issue for now, feel free to reopen it if you think it is still relevant.
