### ISSUE TITLE
Fix `Research Software` Module Title

### ISSUE THREAD

**Issue by Cmurilochem** [esciencecenter-digital-skills/research-software-support#58]
It looks that with the new Nebula update, the title of the `Research Software` module is not show properly. We now get the message:
```
Document is empty, overwrite this content with #empty slot in <ContentDoc>.
```
@JaroCamphuijsen commented about it in https://github.com/esciencecenter-digital-skills/NEBULA/pull/35#issuecomment-2082898253

**Comment by Cmurilochem** [comment]
This issue is no longer necessary as the new NEBULA modules/chapter renderings somewhat solve it.

**Comment by JaroCamphuijsen** [comment]
This issue is still an open issue in NEBULA: https://github.com/esciencecenter-digital-skills/NEBULA/issues/43
This is not an issue on the content repository site so this issue can be closed.
