### ISSUE TITLE
Slides new headings get printed with title

### ISSUE THREAD

**Issue by Cmurilochem** [esciencecenter-digital-skills/research-software-support#70]
There is currently an issue related to the new headings associated with the slides:
```
---
title: What is software?
type: slides
order: 1
---
```
They get printed together with the slides title. We made a dirty hack in order to avoid this by adding an extra initial black slide, before the title one:

![Screenshot 2024-05-16 at 11 44 30 (2)](https://github.com/esciencecenter-digital-skills/research-software-support/assets/114645116/7420e6b2-8da6-44ef-8f89-7b7c1e4e8c27)

I think @raar1 is working on that but I am just in case creating this issue to keep this in our radar.

**Comment by JaroCamphuijsen** [comment]
This is being tackled in https://github.com/esciencecenter-digital-skills/NEBULA/issues/32, it is not an issue with the content of research software support, so I'm closing this issue.
